### ISSUE TITLE
problem in AA2Snowflake 2.3

### ISSUE THREAD

**Issue by xxkiwaxann** [aa2g/AA2Snowflake#12]
hi, i am new at snowflaking, and when i try to open AA2Snowflake, it says:

"AA2Snowflake has crashed. If you were in the middle of an operation, your game may have become corrupt."

help me, plsssss >-<

**Comment by xxkiwaxann** [comment]
A sequência não contém elementos de correspondência
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at AA2Snowflake.formMain.cmbBackground_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\Admin\Documents\GitHub\AA2Snowflake\AA2Snowflake\formMain.cs:line 162
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at AA2Snowflake.formMain.formMain_Load(Object sender, EventArgs e) in C:\Users\Admin\Documents\GitHub\AA2Snowflake\AA2Snowflake\formMain.cs:line 108
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
