### ISSUE TITLE
What does this mean? Sorry I don't speak english :(

### ISSUE THREAD

**Issue by MRLocolow** [aa2g/AA2Snowflake#6]
file:///C:\Users\usuario\AppData\Local\Temp\Rar$EXa1.943\plugins\AA2Data.dll' ni una de sus dependencias. Operación no admitida. (Excepción de HRESULT: 0x80131515)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at PluginLoader.PluginLoader.LoadDLL(String Filename) in C:\Users\Admin\Documents\GitHub\AA2Snowflake\PluginLoader\PluginLoader.cs:line 19
   at PluginLoader.PluginLoader.LoadAllDLLs(String Directory) in C:\Users\Admin\Documents\GitHub\AA2Snowflake\PluginLoader\PluginLoader.cs:line 43
   at AA2Snowflake.formMain.formMain_Load(Object sender, EventArgs e) in C:\Users\Admin\Documents\GitHub\AA2Snowflake\AA2Snowflake\formMain.cs:line 69
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ghost** [comment]
I have just written a page about common issues like the one you have right now. Follow this [guide](https://github.com/aa2g/AA2Snowflake/wiki/Common-Issues).
